module.exports = {
    'CROSSTOWN': 1,
    'LAKE OTIS': 2,
    'NORTHERN LIGHTS': 3,
    'SPENARD/AIRPORT':  7,
    'NORTHWAY': 8,
    'ARCTIC': 9,
    'UNIVERSITY/HOSPITALS': 13,
    'GOVERNMENT HILL': 14,
    '15TH AVE/DEBARR': 15,
    '36TH AVE/WEST ANCHORAGE': 36,
    'MOUNTAIN VIEW': 45,
    'OLD SEWARD': 60,
    'TUDOR': 75,
    'EAGLE RIVER/CHUGIAK': 102
}
