module.exports = {
    'CROSSTOWN': 1,
    'LAKE OTIS': 2,
    'NORTHERN LIGHTS': 3,
    'SPENARD':  7,
    'NORTHWAY': 8,
    'ARCTIC': 9,
    'UNIVERSITY/HOSPITALS': 13,
    'GOVERNMENT HILL': 14,
    '15TH AVE/DEBARR': 15,
    'WEST ANCHORAGE/U-MED': 36,
    'MOUNTAIN VIEW': 45,
    'OLD SEWARD': 60,
    'TUDOR': 75,
    'EAGLE RIVER EXPRESS': 102
}
